orders/urls.py
from django.contrib import admin
from django.urls import include, path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('dashboard', views.OrderView, name='Orders'),
    path('create/', views.CreateOrder, name='Create_Order'),
    path('details/buy/?=<uuid:pk>', views.DisplayBuyOrder.as_view(), name='Order_Details'),
    path('details/sell/?=<uuid:pk>', views.DisplaySellOrder, name='Order_Sell_Details'),
    path('checkout/', views.processOrder, name='Checkout'),
    path('status', views.processOrderStatus, name='OrderStatus'),
    path('status/sell', views.processSellOrder, name='SellOrder'),
    path('buy/', views.Buyorder, name='buy_order'),
    path('buy/eth', views.Buy_eth_order, name='buy_eth_order'),
    path('buy/ltc', views.Buy_ltc_order, name='buy_ltc_order'),
    path('sell/', views.Sellorder, name='sell_order'),
    path('sell/eth', views.Sell_eth_order, name='sell_eth_order'),
    path('sell/ltc', views.Sell_ltc_order, name='sell_ltc_order'),
    path('?=+mnb<uuid:order_id>/success/<hash>', views.OrderSuccess, name='success'),
    path('?=spl<uuid:order_id>/failed/<hash>', views.OrderFailed, name='failed'),
]

pages/urls.py
from django.urls import path

from pages import views

urlpatterns = [
    path('', views.HomePageView, name='home'),
]

sanctum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('users/', include('users.urls')), # new
    path('orders/', include('orders.urls')), # new
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

orders/models.py
from Crypto.Random import random
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
import uuid


# Create your models here.
from django.utils import timezone


class Coins(models.Model):
    title = models.TextField(max_length=200)
    code = models.TextField(max_length=10)

    def __str__(self):
        return self.title



def genrandom():
    num = random.randrange(0,10000)
    num2 = random.randrange(0,10000)
    prefix = "CNP"+str(num)+'-'+str(num2)
    return prefix


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    coin_amount = models.FloatField(null=False, default=0.0)
    price = models.IntegerField(null=False, default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='Orders', on_delete=models.CASCADE)
    coin = models.ForeignKey(Coins, related_name='Coin', on_delete=models.CASCADE)
    order_reference = models.CharField(default=genrandom,max_length=35)
    payment_reference = models.CharField(null=True,blank=True,max_length=35)
    phone = models.IntegerField(null=True,blank=True)
    wallet = models.CharField(null=True,blank=True,max_length=100)
    date_created = models.DateTimeField(default=timezone.now)
    expired = models.BooleanField(default=False)

    PENDING = 'Pending'
    PAID = 'Paid'
    CANCELLED = 'Cancelled'
    FAILED = 'Failed'
    PROCESSING = 'Processing'
    ORDER_STATUS = [
        (PENDING, 'pending'),
        (PAID, 'paid'),
        (CANCELLED, 'cancelled'),
        (PROCESSING, 'Processing'),
        (FAILED, 'failed')]
    order_status = models.CharField(choices=ORDER_STATUS, max_length=50,default=PENDING)
    SELL = 'SELL'
    BUY = 'BUY'
    UNSPECIFIED = 'Unspecified'
    ORDER_TYPE = [
        (SELL, 'Sell'),
        (BUY, 'Buy'),
        (UNSPECIFIED,'Unspecified')]
    order_type = models.CharField(choices=ORDER_TYPE, max_length=50, default=UNSPECIFIED)

    def __str__(self):
        return str(self.id)


class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='Transaction', on_delete=models.CASCADE)
    order = models.OneToOneField(Order, related_name='Orders', on_delete=models.CASCADE)
    amount = models.IntegerField()
    phone = models.IntegerField()
    PENDING = 'Pending'
    PAID = 'Paid'
    CANCELLED = 'Cancelled'
    FAILED = 'Failed'
    PROCESSING = 'Processing'
    TRANSACTION_STATUS = [
        (PENDING, 'pending'),
        (PAID, 'paid'),
        (FAILED, 'failed')]
    order_status = models.CharField(choices=TRANSACTION_STATUS, max_length=50, default=PENDING)

orders/views.py
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, response, HttpResponse, HttpResponseServerError
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
import json
from modules_scripts.modules import *
from modules_scripts.wallets_CB import *

from .models import Order, Coins, Transaction

CB = CoinBase()


def sell_coin_price(coin_amount, coin):
    if coin == "btc":
        rate = getbuyexchange()
        price = getprice()
        amount = float(coin_amount) * float(price["sell"])
        amount = amount * 0.9
        return amount * rate
    if coin == "ltc":
        rate = getbuyexchange()
        price = get_ltc_price()
        amount = float(coin_amount) * float(price["sell"])
        amount = amount * 0.9
        return amount * rate
    if coin == "eth":
        rate = getbuyexchange()
        price = get_eth_price()
        amount = float(coin_amount) * float(price["sell"])
        amount = amount * 0.9
        return amount * rate


def buy_coin_price(coin_amount, coin):
    if coin == "btc":
        rate = getbuyexchange()
        price = getprice()
        amount = float(coin_amount) * float(price["buy"])
        amount = amount * 1.1
        return amount * rate
    if coin == "ltc":
        rate = getbuyexchange()
        price = get_ltc_price()
        amount = float(coin_amount) * float(price["buy"])
        amount = amount * 1.1
        return amount * rate
    if coin == "eth":
        rate = getbuyexchange()
        price = get_eth_price()
        amount = float(coin_amount) * float(price["buy"])
        amount = amount * 1.1
        return amount * rate


# Create your views here.


def OrderView(request):
    try:
        order_list = Order.objects.all().filter(user_id=request.user.id, expired=False, )
        print(order_list.count())
        for order in order_list:
            showablelist = [order.FAILED, order.PAID, order.PROCESSING]
            if ((order.order_status not in showablelist) and (
                    timezone.now() - order.date_created).total_seconds() > 1800):
                order.expired = True
                order.save()
        order_list = order_list.exclude(expired=True)
        print(order_list.count())
        coins = Coins.objects.all()
        context = {'order_list': order_list, 'coins': coins}
        return render(request, 'orders.html', context)
    except Exception as e:
        print(e)
        print(traceback.format_exc())

        raise HttpResponseServerError()


def Buyorder(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = getprice()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(rate) * float(getprice()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'buy.html', context)


def Buy_ltc_order(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = get_ltc_price()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(sellrate) * float(get_ltc_price()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'buy_ltc.html', context)


def Buy_eth_order(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = get_eth_price()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(rate) * float(get_eth_price()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'buy_eth.html', context)


def Sellorder(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = getprice()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(rate) * float(getprice()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'sell.html', context)


def Sell_eth_order(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = get_eth_price()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(rate) * float(get_eth_price()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'sell_eth.html', context)


def Sell_ltc_order(request):
    rate = getbuyexchange()
    sellrate = getsellexchange()
    buy_price = get_ltc_price()['buy']
    buy_price = float(rate) * float(buy_price)
    sell_price = float(rate) * float(get_ltc_price()["sell"])
    context = {'buy_price': buy_price, 'sell_price': sell_price}
    return render(request, 'sell_eth.html', context)


def CreateOrder(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            try:
                if request.POST['order_type'] == "buy":
                    selected_coin = request.POST['coin_type']
                    coin = Coins.objects.get(code__contains=selected_coin.upper())
                    user = get_user_model().objects.get(id=request.user.id)
                    if request.POST['coin_amount']:
                        coin_amount = float(request.POST['coin_amount'])
                        amount = int(buy_coin_price(coin_amount, selected_coin))
                    if request.POST['order_type']:
                        type = request.POST['order_type']
                    order = Order.objects.create(coin_amount=coin_amount, user=user, coin=coin, price=amount)
                    return HttpResponseRedirect(reverse('orders:Order_Details', kwargs={'pk': order.id}))

                elif request.POST['order_type'] == "sell":
                    selected_coin = request.POST['coin_type']
                    coin = Coins.objects.get(code__contains=selected_coin)
                    user = get_user_model().objects.get(id=request.user.id)
                    if request.POST['coin-amount-sell']:
                        coin_amount = float(request.POST['coin-amount-sell'])
                        amount = int(sell_coin_price(coin_amount, selected_coin))
                    if request.POST['order_type']:
                        type = request.POST['order_type']
                    order = Order.objects.create(coin_amount=coin_amount, user=user, coin=coin, price=amount)
                    return HttpResponseRedirect(reverse('orders:Order_Sell_Details', kwargs={'pk': order.id}))

            except Exception as e:
                print(e)
                print(traceback.format_exc())
                raise HttpResponseServerError()
        else:
            rate = getbuyexchange()
            sellrate = getsellexchange()
            buy_price = getprice()['buy']
            buy_price = float(rate) * float(buy_price)
            sell_price = float(sellrate) * float(buy_price)
            context = {'buy_price': buy_price, 'sell_price': sell_price}
            return render(request, 'buy.html', context)
    else:
        if request.method == "POST":
            try:
                if request.POST['order_type'] == "buy":
                    if request.POST['coin_amount']:
                        coin_amount = float(request.POST['coin_amount'])
                    if request.POST['price']:
                        price = int(request.POST['price'])
                    if request.POST['order_type']:
                        type = request.POST['order_type']
                    return redirect('account_login')
                elif request.POST['order_type'] == "sell":
                    if request.POST['coin-amount-sell']:
                        coin_amount_sell = float(request.POST['coin-amount-sell'])
                    if request.POST['price-to-sell']:
                        price_to_sell = int(request.POST['price-to-sell'])
                    if request.POST['order_type']:
                        type = request.POST['order_type']
                    return redirect('account_login')
            except Exception as e:
                print(e)
                print(traceback.format_exc())

                raise HttpResponseServerError()
        else:
            return redirect('account_login')


class DisplayBuyOrder(generic.DetailView):
    model = Order
    template_name = 'orderdetails.html'
    context_object_name = 'order_details'


def DisplaySellOrder(request, pk):
    try:
        if request.method == "POST":
            order = Order.objects.get(id=pk)

            order.phone = request.POST['phone']
            coin = order.coin.code.lower()
            print(coin)
            if len(order.wallet) < 1:
                if coin == "btc":
                    wallet = CB.create_address(CB.btc_id)
                    order.wallet = wallet
                    print("btc wallet created ")
                    order.save()
                elif coin == "ltc":
                    wallet = CB.create_address(CB.ltc_id)
                    order.wallet = wallet
                    order.save()

                elif coin == "eth":
                    wallet = CB.create_address(CB.eth_id)
                    order.wallet = wallet
                    order.save()

            print(order.wallet)
            order.save()
            context = {'order_details': order}
            return render(request, 'sellorderdetails.html', context)
        else:
            order = Order.objects.get(id=pk)
            print(order.wallet)
            context = {'order_details': order}
            return render(request, 'sellorderdetails.html', context)
    except Exception as e:
        print(traceback.format_exc())
        raise HttpResponseServerError()


def OrderSuccess(request, order_id, hash):
    try:
        if check_id(hash, order_id) == True:
            order = Order.objects.get(id=order_id)
            order.order_status = order.PAID
            wallet = order.wallet
            coin = order.coin.code.upper()

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block head_title %}{% endblock %}</title><link rel="icon"
          type="image/png"
          href="{% static "brown/assets/img/icons8-bitcoin-48.png" %}">
    <link rel="stylesheet" href={% static "brown/assets/bootstrap/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href={% static "brown/assets/fonts/fontawesome-all.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/font-awesome.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/ionicons.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/fontawesome5-overrides.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Features-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Footer-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Login-Form-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Navigation-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Sidebar-1.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Sidebar.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/styles.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/cryptofont.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Table-With-Search-1.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Table-With-Search.css" %}>
    {% block extra_head %}
    {% endblock %}
</head>
{% block body %}
    {% block content %}
    {% endblock %}
{% endblock %}
{% block extra_body %}

    <script src={% static "brown/assets/js/jquery.min.js" %}></script>
    <script src={% static "brown/assets/bootstrap/js/bootstrap.min.js" %}></script>
    <script type="module" src={% static "brown/assets/js/prefill.js" %}></script>
    <script src={% static "brown/assets/js/Faq-by-pomdre.js" %}></script>
    <script src={% static "brown/assets/js/Table-With-Search.js" %}></script>
{% endblock %}
</body>
</html>

templates/sell.html
<!DOCTYPE html>
<html>
{% load static %}
{% load socialaccount %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>CoinPesa Sell</title><link rel="icon"
          type="image/png"
          href="{% static "brown/assets/img/icons8-bitcoin-48.png" %}">
    <link rel="stylesheet" href={% static "brown/assets/bootstrap/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href={% static "brown/assets/fonts/fontawesome-all.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/font-awesome.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/ionicons.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/fonts/fontawesome5-overrides.min.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Features-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Footer-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Login-Form-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Navigation-Clean.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Sidebar-1.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Sidebar.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/styles.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Table-With-Search-1.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/Table-With-Search.css" %}>
    <link rel="stylesheet" href={% static "brown/assets/css/cryptofont.min.css" %}>
</head>
<!-- Start of Async Drift Code -->
<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('t7fpbi9wbznu');
</script>
<!-- End of Async Drift Code -->
<body>
<section id="background-section">
     <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
            <div class="container"><a class="navbar-brand" href="{% url 'home' %}"></a><button data-toggle="collapse" class="navbar-toggler custom-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item dropdown" id="dropdown-love"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="{% url 'orders:buy_order'  %}" style="color: #ffffff;">Buy</a>
                            <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="{% url 'orders:buy_order' %}"><i class="cf cf-btc"></i>Bitcoin</a><a class="dropdown-item" role="presentation" href="{% url 'orders:buy_eth_order'  %}"><i class="cf cf-eth"></i>Etherium</a><a class="dropdown-item" role="presentation"
                                    href="{% url 'orders:buy_ltc_order' %}"><i class="cf cf-ltc"></i>Litecoin</a></div>
                        </li>
                        <li class="nav-item" role="presentation"><a class="nav-link" id="sell-link" href="{% url 'orders:sell_order'  %}" style="color: #ffffff;">Sell</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item" role="presentation">
                            <span><a href="{% url 'orders:Orders'  %}" class="btn btn-primary btn-sm rounded" role="button" id="sign-up-btn" style="padding-right: 20px;padding-bottom: 4px;padding-top: 4px;padding-left: 20px;">Account</a>
                                  <a href="{% url 'account_logout'  %}" class="btn btn-primary btn-sm rounded" role="button" id="log-in-btn" style="padding-right: 20px;padding-left: 20px;">Log Out</a>
                            </span>
                        </li>
                        {% else %}

                        <li class="nav-item" role="presentation">
                            <span><a   href="{% url 'account_signup' %}" class="btn btn-primary btn-sm rounded" role="button" id="sign-up-btn" style="padding-right: 20px;padding-bottom: 4px;padding-top: 4px;padding-left: 20px;">Sign Up</a>
                                  <a  href="{% url 'account_login' %}" class="btn btn-primary btn-sm rounded" role="button" id="log-in-btn" style="padding-right: 20px;padding-left: 20px;">Log In</a>
                            </span>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
</section>

<section id="buy-section" class="mb-5">
    <div class="row justify-content-center">
        <div class="col">
            <div class="row">
                <div class="col text-center">
                    <h1>Sell Cryptocurrency</h1>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <div class="row">
                        <div class="col">
                            <p class="text-center">Select Cryptocurrency&nbsp;</p>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-sm-8 col-md-4 col-lg-4 col-xl-4">
                            <div class="dropdown">
                                <button class="btn btn-primary btn-lg dropdown-toggle btn-block" data-toggle="dropdown"
                                        type="button"><i class="cf cf-btc"></i>Bitcoin
                                </button>
                                <div class="dropdown-menu btn-block" role="menu"><a class="dropdown-item"
                                                                                    role="presentation" href="{% url 'orders:sell_ltc_order' %}"><i
                                        class="cf cf-ltc"></i>Litecoin&nbsp;</a><a class="dropdown-item"
                                                                                      role="presentation" href="{% url 'orders:sell_eth_order' %}"><i
                                        class="cf cf-eth"></i>Etherium</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col text-center">
                    <div class="row justify-content-center">
                        <div class="col-sm-8 col-md-4 col-lg-4 col-xl-4">
                            <form action="{% url 'orders:Create_Order' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <p>Prices include fees. Additional charges for methods of payment may apply.</p>
                                    <div class="input-group border rounded"><input required step="0.00000001"
                                                                                   id="coin-amount-buy"
                                                                                   name="coin-amount-sell"
                                                                                   class="form-control" type="number">
                                        <div class="input-group-append">
                                            <button class="btn" type="button">BTC</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group border rounded">
                                        <input required step="0.01" id="price-to-sell" max="70000" min="500"  name="price-to-sell"
                                               class="form-control" type="number">
                                        <div class="input-group-append">
                                            <button class="btn" type="button">KES</button>
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="coin_type" value="btc" readonly>
                                <input type="hidden" name="order_type" value="sell" readonly>
                                <button class="btn btn-primary btn-block" type="submit">Sell Now</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="footer-clean" style="background-size: cover;background-repeat: no-repeat;">
     <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Site Map</h3>
                        <ul>
                            <li><a href="{% url 'orders:buy_order'  %}">Buy Coins</a></li>
                            <li><a href="{% url 'orders:sell_order'  %}">Sell Coins</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Legacy</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Help</h3>
                        <ul>
                            <li><a href="support">Support</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a>
                        <p class="copyright">Archers Den © 2019</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
{{ buy_price|json_script:"buy-price" }}

<script src={% static "brown/assets/js/jquery.min.js" %}></script>
<script src={% static "brown/assets/js/buyprice.js" %}></script>
<script src={% static "brown/assets/bootstrap/js/bootstrap.min.js" %}></script>
<script src={% static "brown/assets/js/Faq-by-pomdre.js" %}></script>
<script src={% static "brown/assets/js/Table-With-Search.js" %}></script>
</body>

</html>